//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPSG_Jefe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SPSG_Jefe()
        {
            this.SPSG_Empleado_Jefe = new HashSet<SPSG_Empleado_Jefe>();
        }
    
        public int sjfe_Id { get; set; }
        public string sjfe_Nombre { get; set; }
        public string sjfe_Correo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPSG_Empleado_Jefe> SPSG_Empleado_Jefe { get; set; }
    }
}
