//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Entities;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SPSGEntities : DbContext
    {
        public SPSGEntities(string strConnection)
            : base("name=SPSGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SPSG_Empleado> SPSG_Empleado { get; set; }
        public virtual DbSet<SPSG_Empleado_Jefe> SPSG_Empleado_Jefe { get; set; }
        public virtual DbSet<SPSG_Jefe> SPSG_Jefe { get; set; }
    
        public virtual ObjectResult<SP_GET_EMPLEADO_Result> SP_GET_EMPLEADO(string nombre, string correo, Nullable<int> pagina, Nullable<int> filas)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var paginaParameter = pagina.HasValue ?
                new ObjectParameter("pagina", pagina) :
                new ObjectParameter("pagina", typeof(int));
    
            var filasParameter = filas.HasValue ?
                new ObjectParameter("filas", filas) :
                new ObjectParameter("filas", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_EMPLEADO_Result>("SP_GET_EMPLEADO", nombreParameter, correoParameter, paginaParameter, filasParameter);
        }
    
        public virtual ObjectResult<SP_GET_JEFE_Result> SP_GET_JEFE(string nombre, string correo, Nullable<int> pagina, Nullable<int> filas)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var paginaParameter = pagina.HasValue ?
                new ObjectParameter("pagina", pagina) :
                new ObjectParameter("pagina", typeof(int));
    
            var filasParameter = filas.HasValue ?
                new ObjectParameter("filas", filas) :
                new ObjectParameter("filas", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_JEFE_Result>("SP_GET_JEFE", nombreParameter, correoParameter, paginaParameter, filasParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_SET_EMPLEADO(Nullable<int> semp_Id, string nombre, string correo, string json_sjfe_Id)
        {
            var semp_IdParameter = semp_Id.HasValue ?
                new ObjectParameter("semp_Id", semp_Id) :
                new ObjectParameter("semp_Id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var json_sjfe_IdParameter = json_sjfe_Id != null ?
                new ObjectParameter("json_sjfe_Id", json_sjfe_Id) :
                new ObjectParameter("json_sjfe_Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_SET_EMPLEADO", semp_IdParameter, nombreParameter, correoParameter, json_sjfe_IdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_SET_JEFE(Nullable<int> sjfe_Id, string nombre, string correo, string json_semp_Id)
        {
            var sjfe_IdParameter = sjfe_Id.HasValue ?
                new ObjectParameter("sjfe_Id", sjfe_Id) :
                new ObjectParameter("sjfe_Id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var json_semp_IdParameter = json_semp_Id != null ?
                new ObjectParameter("json_semp_Id", json_semp_Id) :
                new ObjectParameter("json_semp_Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_SET_JEFE", sjfe_IdParameter, nombreParameter, correoParameter, json_semp_IdParameter);
        }
    }
}
